### ISSUE TITLE
How

### ISSUE THREAD

**Issue by Z-Droid** [iTXTech/GeniRCON#2]
How do we use the "connect" command?

**Comment by Wolfurama** [comment]
I wana know the same thing i think dont work just i dont know .-.

**Comment by Z-Droid** [comment]
Ikr

**Comment by PeratX** [comment]
type /help connect.
1. change enable-rcon=on in server.properties
2. open GeniRCON Client
3. type /connect <address> <port> <password> <timeout> (SessionID)

**Comment by Wolfurama** [comment]
Sesión id?

**Comment by Wolfurama** [comment]
Cant tells time out error on sdcard data...

**Comment by Z-Droid** [comment]
What's "time out" or session ID like you said

**Comment by PeratX** [comment]
Timeout = any time you like xD. SessionId can be empty

**Comment by Z-Droid** [comment]
Lol k
