### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/GeniRCON#3]
I make connect and its not work what mus i write to connect to a server i have maked connect theip:port

**Comment by ishitatsuyuki** [comment]
Please speak English.

**Comment by erkam2002** [comment]
How can i connect to a Server?

**Comment by PeratX** [comment]
Type /help connect

**Comment by Wolfurama** [comment]
Type /connect ip (only works local?) port, rconpassword and timeout (just 15 or whatever)

**Comment by PeratX** [comment]
/connect xxx.xxx.xxx.xxx ### ****** 5

xxx.xxx.xxx.xxx Server address or Server IP
### Port
****** Password

**Comment by GlitchPlayer** [comment]
Also, before connecting to a IP address... make sure the port is port forwarded...
