### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by MasterWolf** [iTXTech/GeniRCON#4]
it stucks at "connecting"...

**Comment by PeratX** [comment]
Use IP

**Comment by MasterWolf** [comment]
@PeratX i filled everything good

**Comment by MasterWolf** [comment]
As you said 
> 3. type /connect (address) (port) (password) (timeout) (SessionID)

**Comment by GlitchPlayer** [comment]
Try to port forward the IP you were using... Common mistakes

**Comment by theshaderman** [comment]
my APK dont work xD
